### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by gitroli** [hschiebold/ep3-bs#25]
Konnte es seit längerem jetzt auch mal testen, bekomme leider eine Menge Fehler:

```
Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/vhosts/xxx/vendor/zendframework/zend-stdlib/src/ArrayObject.php on line 426

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, Zend\I18n\Translator\TextDomain given in /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php:52 Stack trace: #0 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php(52): array_key_exists() #1 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Translator.php(711): Zend\I18n\Translator\Loader\PhpArray->load() #2 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Translator.php(620): Zend\I18n\Translator\Translator->loadMessagesFromPatterns() #3 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Translator.php(442): Zend\I18n\Translator\Translator->loadMessages() #4 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Translator.php(356): Zend\I18n\Translator\Translator->getTranslatedMessage() #5 /var/www/vhosts/xxx/vendor/zendframework/zend-mvc/src/I18n/Translator.php(73): Zend\I18n\Translator\Translator->translate() #6 /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/View/Helper/Translate.php(38): Zend\Mvc\I18n\Translator->translate() #7 [internal function]: Zend\I18n\View\Helper\Translate->__invoke() #8 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array() #9 /var/www/vhosts/xxx/module/Base/src/Base/View/Helper/Setup.php(15): Zend\View\Renderer\PhpRenderer->__call() #10 [internal function]: Base\View\Helper\Setup->__invoke() #11 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array() #12 /var/www/vhosts/xxx/module/Base/view/error/500.phtml(4): Zend\View\Renderer\PhpRenderer->__call() #13 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('...') #14 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render() #15 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render() #16 /var/www/vhosts/xxx/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren() #17 /var/www/vhosts/xxx/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render() #18 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render() #19 /var/www/vhosts/xxx/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func() #20 /var/www/vhosts/xxx/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners() #21 /var/www/vhosts/xxx/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(123): Zend\EventManager\EventManager->triggerEvent() #22 [internal function]: Zend\Mvc\View\Http\DefaultRenderingStrategy->render() #23 /var/www/vhosts/xxx/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func() #24 /var/www/vhosts/xxx/vendor/zendframework/zend-eventmanager/src/EventManager.php(248): Zend\EventManager\EventManager->triggerListeners() #25 /var/www/vhosts/xxx/vendor/zendframework/zend-mvc/src/Application.php(384): Zend\EventManager\EventManager->triggerEvent() #26 /var/www/vhosts/xxx/vendor/zendframework/zend-mvc/src/Application.php(356): Zend\Mvc\Application->completeRequest() #27 /var/www/vhosts/xxx/public/index.php(66): Zend\Mvc\Application->run() #28 {main} thrown in /var/www/vhosts/xxx/vendor/zendframework/zend-i18n/src/Translator/Loader/PhpArray.php on line 52

```

**Comment by hschiebold** [comment]
Du hast wie im Ticket beschrieben den entsprechenden branch von mir genutzt und den autoloader initialisiert? 

Die Fehler kommen ja alle von den Standard Zens Klassen, die Tobias überschrieben hat. 

Welche PHP Version ist bei dir im Einsatz?

**Comment by gitroli** [comment]
Ja ich habe den branch benutzt.

Ich habe keinen Shellzugriff, gibt es eine andere Möglichkeit den composer bzw autoloader zu initialisieren?

PHP ist 8.1

**Comment by hschiebold** [comment]
"Ich habe keinen Shellzugriff, gibt es eine andere Möglichkeit den composer bzw autoloader zu initialisieren?"

ach herje - kein Ahnung so richtig - Tobias hat das glaube ich über das einchecken der composer.lock bei seinem Überschreiben der ganzen Zend Klassen geregelt - ich hatte aber keinen Bock das irgendwie manuell zu mergen bzw. das nicht hinbekommen und da ja der autoloader die Arbeit für mich macht ...

Ich habe mal meinen vendor/composer path in den betreffenden branch eingecheckt - der wird ja glaube ich durch den Aufruf des dump autoloader Prozesses aktualisiert - vielleicht hilft das ja

**Comment by hschiebold** [comment]
Das Wichtige hierbei ist ja, dass der autoloader die von Tobias übeschriebenen Zend Klassen im src Pfad findet und nicht die Standard Zend Klassen benutzt, da diese nicht mit PHP 8 kompatibel sind

**Comment by gitroli** [comment]
Jetzt wird es spannend, jetzt bekomme ich einen HTTP 500 Error

**Comment by hschiebold** [comment]
konkrete Fehlermeldung aus log ?

**Comment by gitroli** [comment]
```
AH01071: Got error 'PHP message: PHP Warning: require(/var/www/vhosts/xxx/vendor/composer/platform_check.php): Failed to open stream: No such file or directory in /var/www/vhosts/xxx/vendor/composer/autoload_real.php on line 25PHP message: PHP Fatal error: Uncaught Error: Failed opening required '/var/www/vhosts/xxx/vendor/composer/platform_check.php' (include_path='.:/opt/plesk/php/8.1/share/pear') in /var/www/vhosts/xxx/vendor/composer/autoload_real.php:25\nStack trace:\n#0 /var/www/vhosts/xxx/vendor/autoload.php(7): ComposerAutoloaderInit80187b261285ce6ecce57578ecc7afb2::getLoader()\n#1 /var/www/vhosts/xxx/public/index.php(50): require('...')\n#2 {main}\n thrown in /var/www/vhosts/xxx/vendor/composer/autoload_real.php on line 25'
```

**Comment by hschiebold** [comment]
die platform_check.php hab ich vorhin auf die Schnelle beim einchecken übersehen - ist jetzt drin

**Comment by gitroli** [comment]
Jetzt läuft die Seite und derzeit auch keine Fehler, ich teste noch weiter.

**Comment by gitroli** [comment]
mit PHP 8.2 und 8.3 bekomme ich die Fehler:
<img width="1145" alt="image" src="https://github.com/hschiebold/ep3-bs/assets/31999445/8fe423a0-c93f-4a75-857a-782385d692f2">

**Comment by hschiebold** [comment]
Für 8.2 und 8.3 wird dann vermutlich noch mehr überschrieben werden müssen

**Comment by gitroli** [comment]
Ich schließe mal das Issue, unter 8.1 läuft es jetzt, danke nochmals, > 8.1 kommen die Fehler aus dem Bild von vorhin.

**Comment by hschiebold** [comment]
in der init.php kannst du auch die deprecated Meldungen unterdrücken - dann scheint es auch mit 8.2 und 8. 3 zu laufen

ini_set('error_reporting', E_ALL & ~E_USER_DEPRECATED & ~E_DEPRECATED);

**Comment by gitroli** [comment]
sieht gut aus auf den ersten blick
